#!/usr/bin/env python3
"""
Notion OAuth Setup Script

Simplified script using the reusable NotionOAuthClient class.
This script handles the OAuth flow and saves tokens to .env.qa

Usage:
    python scripts/notion_oauth_setup.py
"""

import sys
import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env.qa for OAuth credentials
env_file = Path(__file__).parent.parent / ".env.qa"
if env_file.exists():
    load_dotenv(env_file)
    print("✓ Loaded .env.qa for OAuth credentials")
else:
    # Fallback to default .env
    load_dotenv()
    print("⚠ Warning: .env.qa not found, using default .env")

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from logger import get_logger
from services.notion_oauth_client import NotionOAuthClient

logger = get_logger(__name__)


def save_token_to_env(token_data: dict, env_file: str = ".env.qa"):
    """Save OAuth token to environment file."""
    env_path = Path(env_file)
    
    # Read existing content
    if env_path.exists():
        with open(env_path, 'r') as f:
            lines = f.readlines()
    else:
        lines = []
    
    # Update or add OAuth token
    access_token = token_data.get('access_token')
    workspace_name = token_data.get('workspace_name', 'Unknown')
    workspace_id = token_data.get('workspace_id', '')
    
    # Remove old OAuth token lines
    lines = [line for line in lines if not line.startswith('NOTION_OAUTH_ACCESS_TOKEN=')]
    lines = [line for line in lines if not line.startswith('NOTION_OAUTH_WORKSPACE_ID=')]
    lines = [line for line in lines if not line.startswith('NOTION_OAUTH_WORKSPACE_NAME=')]
    
    # Add new OAuth token
    lines.append(f"\n# OAuth Configuration (Generated by notion_oauth_setup.py)\n")
    lines.append(f"NOTION_OAUTH_ACCESS_TOKEN={access_token}\n")
    lines.append(f"NOTION_OAUTH_WORKSPACE_ID={workspace_id}\n")
    lines.append(f"NOTION_OAUTH_WORKSPACE_NAME={workspace_name}\n")
    
    # Write back
    with open(env_path, 'w') as f:
        f.writelines(lines)
    
    logger.info(f"✓ Saved OAuth token to {env_file}")
    logger.info(f"  Workspace: {workspace_name}")


def main():
    """Main OAuth setup flow."""
    logger.info("=" * 60)
    logger.info("Notion OAuth Setup")
    logger.info("=" * 60)
    
    # Get OAuth credentials from environment
    client_id = os.getenv("NOTION_OAUTH_CLIENT_ID")
    client_secret = os.getenv("NOTION_OAUTH_CLIENT_SECRET")
    
    if not client_id or not client_secret:
        logger.error("Missing OAuth credentials!")
        logger.error("\nPlease set in your .env file:")
        logger.error("  NOTION_OAUTH_CLIENT_ID=your-client-id")
        logger.error("  NOTION_OAUTH_CLIENT_SECRET=your-client-secret")
        logger.error("\nGet these from: https://www.notion.so/my-integrations")
        logger.error("  1. Create a 'Public integration'")
        logger.error("  2. Add redirect URI: http://localhost:8080/oauth/callback")
        logger.error("  3. Enable 'Insert content' capability")
        sys.exit(1)
    
    # Create OAuth client
    oauth_client = NotionOAuthClient(
        client_id=client_id,
        client_secret=client_secret,
        redirect_uri="http://localhost:8080/oauth/callback"
    )
    
    logger.info("\nStarting OAuth flow...")
    
    try:
        # Execute OAuth flow
        token_data = oauth_client.authorize(
            auto_open_browser=True,
            on_success=lambda data: logger.info(f"✓ Connected to workspace: {data.get('workspace_name', 'Unknown')}"),
            on_error=lambda error: logger.error(f"✗ OAuth failed: {error}")
        )
        
        # Save to .env.qa
        save_token_to_env(token_data, ".env.qa")
        
        logger.info("\n" + "=" * 60)
        logger.info("✓ OAuth Setup Complete!")
        logger.info("=" * 60)
        logger.info("\nToken saved to .env.qa")
        logger.info("\nYou can now run:")
        logger.info("  python scripts/setup_qa_environment.py setup")
        logger.info("\nThe script will use OAuth authentication automatically.")
        logger.info("=" * 60)
        
    except Exception as e:
        logger.error(f"\n✗ Failed to complete OAuth setup: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()